### ISSUE TITLE
为什么我这两个都用不了

### ISSUE THREAD

**Issue by chuckiesong** [yuuuuuuer/wzxy_SWPU#2]
手动抓包的显示<Response [200]>，；自动抓包的显示Invalid header value b'\n'

**Comment by chuckiesong** [comment]
自动抓包的可以了，手动抓包的还是不行，还显示<Response [200]>

**Comment by yuuuuuuer** [comment]
> 自动抓包的可以了，手动抓包的还是不行，还显示<Response [200]>

显示200是代表交换数据成功了。 200代码是http协议中代表success的。
如果你使用response.text  获取这条消息的文本 就能看到成功的消息。

**Comment by chuckiesong** [comment]
> > 自动抓包的可以了，手动抓包的还是不行，还显示<Response [200]>
> 
> 显示200是代表交换数据成功了。 200代码是http协议中代表success的。
> 如果你使用response.text  获取这条消息的文本 就能看到成功的消息。

 解决了，JWSESSION的原因，我自己用小黄鸟抓的包里面的JWESESSION和你这个程序自动 抓的不一样，改了就成功了
